name: Product The Novel
favicon: null
layout_spectrum: 0.6466350639238954
typography_spectrum: 0.04725423757918179
title: The Product Line
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4b4640'
    - '#806459'
    - '#ae927c'
    - '#f4f1ea'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
